import {
  HTMLHarvest,
  CandidateItem,
  IntentRecord,
  RequirementSpec,
  SystemCanonicalSpec,
  DeliberationAgenda,
  ImplementationPlan,
  WorkRequestDCO,
  WRPKernelDelta,
  SystemNode,
  ModelChainConfig,
  SystemStatus,
} from '../types/conduit';

export const INITIAL_SYSTEM_STATUS: SystemStatus = {
  pgConnected: true,
  pgDsn: 'postgresql://nexus_admin:***@postgres.internal.nexus:5432/nexus',
  pgSchema: 'conduit',
  wrpKernelActive: true,
  wrpKernelUrl: 'http://localhost:3103',
  mcpServerUrl: 'http://localhost:3100',
  activeLeasesCount: 3,
  circuitBreakerTripped: false,
  lastSyncTimestamp: '2026-07-24T12:00:15Z',
};

export const INITIAL_HARVESTS: HTMLHarvest[] = [
  {
    id: 'HARVEST-2026-001',
    title: 'Autonomous Executor Resilience & Model Chain Fallback Transcript',
    sourceUrl: 'https://transcripts.nexus.internal/harvests/2026-07-20/executor-resilience.html',
    ingestedAt: '2026-07-20T14:32:00Z',
    author: 'HarvestBot-Agent-09',
    candidateCount: 4,
    tags: ['Resilience', 'ADR-006', 'ModelChain', 'ExecutionAuthority'],
    rawHtmlContent: `
      <article class="transcript-harvest">
        <h2>Engineering Review Transcript: Model Chain Resilience & ADR-006 Dispatches</h2>
        <p class="meta"><strong>Date:</strong> 2026-07-20 | <strong>Participants:</strong> Principal Architect, Agent Conduit Core, Kernel Bot</p>
        <section class="dialogue">
          <p><strong>[Architect]:</strong> We observed intermittent 429 rate limits from tackle-mcp when the primary model is inundated during large codebase sweeps. We need automatic retry loops and secondary model fallback without dropping execution leases.</p>
          <p><strong>[Conduit Agent]:</strong> Under ADR-006, the lease should remain acquired during in-place rate-limit retries up to 5 attempts (300s backoff). If primary fails twice consecutively, fallback to <code>gemini-1.5-pro</code> or <code>claude-3-5-sonnet</code>.</p>
          <p><strong>[Kernel Bot]:</strong> Replay receipts must log the exact model fallback transition to ensure deterministic snapshot reconstruction in WRP Kernel.</p>
        </section>
      </article>
    `,
  },
  {
    id: 'HARVEST-2026-002',
    title: 'WRP Kernel Deterministic Delta Replay & State Lineage Harvest',
    sourceUrl: 'https://transcripts.nexus.internal/harvests/2026-07-22/wrp-kernel-replay.html',
    ingestedAt: '2026-07-22T09:15:00Z',
    author: 'KernelReview-Agent',
    candidateCount: 3,
    tags: ['WRPKernel', 'Replay', 'Lineage', 'PostgreSQL'],
    rawHtmlContent: `
      <article class="transcript-harvest">
        <h2>WRP Kernel Engine Synchronization Session</h2>
        <p>Discussion on <code>vision.receipts</code> polling daemon vs HTTP <code>/delta</code> batch ingestion. Ensure sha256 receipt chaining matches kernel delta reduction state.</p>
      </article>
    `,
  },
  {
    id: 'HARVEST-2026-003',
    title: 'Agent Budget Enforcement & Per-Role Token Cost Cap Transcript',
    sourceUrl: 'https://transcripts.nexus.internal/harvests/2026-07-23/budget-caps.html',
    ingestedAt: '2026-07-23T11:45:00Z',
    author: 'FinanceAuditBot',
    candidateCount: 2,
    tags: ['Budget', 'TokenCost', 'CircuitBreaker'],
    rawHtmlContent: `
      <article class="transcript-harvest">
        <h2>Token Estimator & Agent Budget Guardrails</h2>
        <p>When agent budget usage in <code>tackle.agent_budget_usage</code> exceeds the $500.00 ceiling, Conduit must issue a <code>BLOCK</code> receipt with exit code 4.</p>
      </article>
    `,
  },
];

export const INITIAL_CANDIDATES: CandidateItem[] = [
  {
    id: 'CND-801',
    harvestId: 'HARVEST-2026-001',
    title: 'Implement In-Place Model Chain Fallback with Rate-Limit Backoff',
    description: 'When primary model yields HTTP 429 or transient API error, try fallback chain ordered by priority prior to dropping lease.',
    severity: 'HIGH',
    category: 'refactor',
    status: 'converted_to_intent',
    createdAt: '2026-07-20T15:00:00Z',
    suggestedSystem: 'nexus.conduit.executor_cloud',
  },
  {
    id: 'CND-802',
    harvestId: 'HARVEST-2026-001',
    title: 'Enforce Mutual Exclusion via Lease TTL in Execution Authority (ADR-006)',
    description: 'Ensure attempt lock lease is acquired prior to subprocess invocation and released atomically upon receipt generation.',
    severity: 'CRITICAL',
    category: 'architecture',
    status: 'converted_to_intent',
    createdAt: '2026-07-20T15:10:00Z',
    suggestedSystem: 'nexus.conduit.db_adapter',
  },
  {
    id: 'CND-803',
    harvestId: 'HARVEST-2026-002',
    title: 'WRP Kernel In-Process Fast Delta Engine Bridge Sync Daemon',
    description: 'Poll vision.receipts continuously and push mapped KernelDeltas into FastAPI Kernel server at port 3103.',
    severity: 'MEDIUM',
    category: 'feature',
    status: 'converted_to_intent',
    createdAt: '2026-07-22T10:00:00Z',
    suggestedSystem: 'nexus.kernel.bridge',
  },
  {
    id: 'CND-804',
    harvestId: 'HARVEST-2026-003',
    title: 'Agent Budget Ceiling Block Receipt Trigger',
    description: 'Trigger BLOCK receipt and stop ticket dispatch when tackle.agent_budget_usage exceeds USD limit.',
    severity: 'HIGH',
    category: 'security',
    status: 'unassigned',
    createdAt: '2026-07-23T12:00:00Z',
    suggestedSystem: 'nexus.conduit.budget',
  },
];

export const INITIAL_INTENTS: IntentRecord[] = [
  {
    id: 'INT-301',
    candidateId: 'CND-801',
    systemId: 'SYS-CONDUIT',
    subsystemId: 'SUB-EXECUTOR',
    summary: 'Model Chain Resilient Dispatch Engine',
    intentScope: 'Provide seamless model degradation path for Planner, Builder, and Reviewer roles under load.',
    impactScore: 9,
    status: 'promoted_to_requirement',
    createdAt: '2026-07-21T08:30:00Z',
    targetOutcome: 'Zero failed dispatches due to transient vendor rate limits or single-model outages.',
  },
  {
    id: 'INT-302',
    candidateId: 'CND-802',
    systemId: 'SYS-CONDUIT',
    subsystemId: 'SUB-DB-ADAPTER',
    summary: 'ADR-006 Execution Authority Protocol & Leases',
    intentScope: 'Guaranteed execution mutual exclusion, attempt tracing, and execution receipts in PostgreSQL nexus.',
    impactScore: 10,
    status: 'promoted_to_requirement',
    createdAt: '2026-07-21T09:00:00Z',
    targetOutcome: 'Single active executor per WorkRequest with full immutable audit history.',
  },
  {
    id: 'INT-303',
    candidateId: 'CND-803',
    systemId: 'SYS-KERNEL',
    subsystemId: 'SUB-BRIDGE',
    summary: 'Kernel Delta Lineage & Replay Daemon',
    intentScope: 'Bridge conduit.receipts to WRP Kernel Engine with state snapshot hash calculation.',
    impactScore: 8,
    status: 'draft',
    createdAt: '2026-07-22T11:00:00Z',
    targetOutcome: 'Deterministic state replay from any historic receipt snapshot.',
  },
];

export const INITIAL_REQUIREMENTS: RequirementSpec[] = [
  {
    id: 'REQ-MODELCHAIN-001',
    intentId: 'INT-301',
    codeName: 'REQ-MODEL-CHAIN-FALLBACK',
    title: 'Multi-Model Fallback Chain with In-Place Retries',
    acceptanceCriteria: [
      'Primary model resolved via get_role_model_config(role)',
      'Fallback array sorted by priority from tackle-mcp',
      'In-place retry loop handles HTTP 429 with API_LIMIT_RETRY_DELAY backoff',
      'If all models exhausted, generate retry ticket and mark attempt FAILED',
    ],
    priority: 'P0',
    status: 'canonicalized',
    estimatedComplexity: 'M',
    createdAt: '2026-07-21T10:00:00Z',
  },
  {
    id: 'REQ-ADR006-002',
    intentId: 'INT-302',
    codeName: 'REQ-EXECUTION-AUTHORITY',
    title: 'ADR-006 Strict Execution Leases & Receipt Chain',
    acceptanceCriteria: [
      'Acquire TTL lease per request in conduit.leases table',
      'Log attempt in conduit.attempts before subprocess spawn',
      'Issue execution receipt signed with plan hash',
      'Atomic lease release on completion or fatal error',
    ],
    priority: 'P0',
    status: 'canonicalized',
    estimatedComplexity: 'L',
    createdAt: '2026-07-21T11:30:00Z',
  },
];

export const INITIAL_CANONICAL_SPECS: SystemCanonicalSpec[] = [
  {
    id: 'SPEC-CONDUIT-001',
    requirementId: 'REQ-MODELCHAIN-001',
    systemName: 'nexus.conduit.orchestrator',
    subsystemName: 'model_chain_dispatcher',
    specVersion: '2.4.0-ADR006',
    architectureSummary: 'Central dispatch loop reading nexus.conduit.tickets, resolving model chain, and executing with lease locks.',
    apiContracts: [
      'resolve_model_chain(role: AgentRole) -> List[ModelConfig]',
      'dispatch_work_request(wr: WorkRequestDCO) -> ExecutionResult',
      'check_budget_limits(role: AgentRole) -> BudgetStatus',
    ],
    moduleBoundaries: [
      'main.py',
      'db_adapter.py',
      'executor_cloud.py',
      'token_estimator.py',
    ],
    status: 'canonical',
    updatedAt: '2026-07-22T14:00:00Z',
  },
  {
    id: 'SPEC-KERNEL-002',
    requirementId: 'REQ-ADR006-002',
    systemName: 'nexus.kernel.engine',
    subsystemName: 'wrp_kernel_runtime',
    specVersion: '1.8.2-KERNEL',
    architectureSummary: 'Deterministic, replayable state engine consuming KernelDeltas from bridge sync daemon.',
    apiContracts: [
      'POST /delta (ingest deltas)',
      'GET /state (inspect state hash)',
      'GET /replay (replay from snapshot)',
    ],
    moduleBoundaries: [
      'bridge/conduit_bridge.py',
      'wrp_kernel/engine.py',
      'app/main.py (FastAPI port 3103)',
    ],
    status: 'canonical',
    updatedAt: '2026-07-23T09:00:00Z',
  },
];

export const INITIAL_AGENDAS: DeliberationAgenda[] = [
  {
    id: 'AGENDA-2026-075',
    specId: 'SPEC-CONDUIT-001',
    title: 'Model Chain Fallback Feasibility & Executor Lease Timeout Review',
    proposedByRole: 'planner',
    createdAt: '2026-07-22T16:00:00Z',
    status: 'CONSENSUS_REACHED',
    feasibilityConsensusScore: 94,
    participants: [
      {
        agentId: 'agent-planner-01',
        name: 'Planner Agent AI',
        role: 'planner',
        model: 'gemini-1.5-pro',
        vote: 'APPROVE',
        feasibilityScore: 96,
        comments: 'Model chain specification aligns with ADR-006 and avoids orphaned work requests.',
      },
      {
        agentId: 'agent-builder-04',
        name: 'Builder Agent Core',
        role: 'builder',
        model: 'claude-3-5-sonnet',
        vote: 'APPROVE',
        feasibilityScore: 92,
        comments: 'Verified executor_cloud parsing and DCO result emission compatibility.',
      },
      {
        agentId: 'agent-reviewer-02',
        name: 'Reviewer Authority',
        role: 'reviewer',
        model: 'gpt-4o',
        vote: 'APPROVE',
        feasibilityScore: 95,
        comments: 'Receipt signature verification logic passes cryptographically.',
      },
      {
        agentId: 'agent-kernel-01',
        name: 'Kernel Guard',
        role: 'kernel',
        model: 'wrp-kernel-validator',
        vote: 'NEUTRAL',
        feasibilityScore: 90,
        comments: 'Requires continuous kernel-sync-daemon polling every 3 minutes.',
      },
    ],
    discussionTranscript: [
      {
        timestamp: '2026-07-22T16:05:00Z',
        agentId: 'agent-planner-01',
        agentName: 'Planner Agent AI',
        role: 'planner',
        text: 'Proposal: Introduce 3-tier fallback chain (Primary: Claude 3.5 Sonnet, Fallback 1: Gemini 1.5 Pro, Fallback 2: PIPELINE_MODEL env var) with in-place 300s retries.',
      },
      {
        timestamp: '2026-07-22T16:08:00Z',
        agentId: 'agent-builder-04',
        agentName: 'Builder Agent Core',
        role: 'builder',
        text: 'Tested mock rates: With 5 retry attempts, 98.4% of rate-limited dispatches recover without tripping circuit breaker.',
      },
      {
        timestamp: '2026-07-22T16:12:00Z',
        agentId: 'agent-reviewer-02',
        agentName: 'Reviewer Authority',
        role: 'reviewer',
        text: 'Consensus confirmed. Promoting to Implementation Plan 0075.',
      },
    ],
    summaryOutput: 'Approved for promotion to Plan 0075 with 94% overall feasibility consensus.',
  },
  {
    id: 'AGENDA-2026-076',
    specId: 'SPEC-KERNEL-002',
    title: 'WRP Kernel Fast Delta Replay API Server Optimization',
    proposedByRole: 'kernel',
    createdAt: '2026-07-23T14:00:00Z',
    status: 'IN_DELIBERATION',
    feasibilityConsensusScore: 82,
    participants: [
      {
        agentId: 'agent-planner-01',
        name: 'Planner Agent AI',
        role: 'planner',
        model: 'gemini-1.5-pro',
        vote: 'APPROVE',
        feasibilityScore: 88,
        comments: 'Good addition for observability.',
      },
      {
        agentId: 'agent-builder-04',
        name: 'Builder Agent Core',
        role: 'builder',
        model: 'claude-3-5-sonnet',
        vote: 'NEUTRAL',
        feasibilityScore: 78,
        comments: 'Need to ensure SQLite/PostgreSQL bridge does not lock during bulk delta replay.',
      },
    ],
    discussionTranscript: [
      {
        timestamp: '2026-07-23T14:10:00Z',
        agentId: 'agent-kernel-01',
        agentName: 'Kernel Guard',
        role: 'kernel',
        text: 'Proposing fast memory-mapped snapshot caching for /replay endpoint on FastAPI port 3103.',
      },
    ],
  },
];

export const INITIAL_PLANS: ImplementationPlan[] = [
  {
    id: 'plan_0075',
    ticketId: 'TCK-2026-0075',
    title: 'Model Chain Resilient Dispatch & ADR-006 Lease Enforcement',
    description: 'Implement multi-model fallback chain (primary + fallback models) and execution authority protocol with receipt signature validation.',
    specId: 'SPEC-CONDUIT-001',
    status: 'ACTIVE',
    currentRole: 'builder',
    modelChain: ['claude-3-5-sonnet', 'gemini-1.5-pro', 'gpt-4o-mini'],
    activeModel: 'claude-3-5-sonnet',
    costUsd: 14.85,
    tokenCount: 428000,
    createdAt: '2026-07-22T17:00:00Z',
    updatedAt: '2026-07-24T11:45:00Z',
    leaseOwner: 'executor-cloud-node-01',
    retryAttempts: 0,
    receipts: [
      {
        id: 'RCP-0075-1',
        ticketId: 'TCK-2026-0075',
        receiptType: 'PROPOSED',
        issuedAt: '2026-07-22T17:05:00Z',
        payload: { proposedBy: 'PlannerAgent', reason: 'Initial ingestion from HARVEST-2026-001' },
        hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      },
      {
        id: 'RCP-0075-2',
        ticketId: 'TCK-2026-0075',
        receiptType: 'PLANNING',
        issuedAt: '2026-07-22T18:00:00Z',
        payload: { plannerModel: 'gemini-1.5-pro', scope: 'Full ADR-006 compliance' },
        hash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
        previousHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
      },
      {
        id: 'RCP-0075-3',
        ticketId: 'TCK-2026-0075',
        receiptType: 'PLAN_CREATE',
        issuedAt: '2026-07-23T08:30:00Z',
        payload: { dcoCount: 3, workRequestsGenerated: ['WR-2026-088', 'WR-2026-089'] },
        hash: '7d85311904a43a0db02e1dd31f9b33a8e94fae4860b0d91244e05ef0319ed02e',
        previousHash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
      },
      {
        id: 'RCP-0075-4',
        ticketId: 'TCK-2026-0075',
        receiptType: 'IMPLEMENTATION',
        issuedAt: '2026-07-24T10:15:00Z',
        payload: { builderModel: 'claude-3-5-sonnet', status: 'IN_PROGRESS', leaseId: 'LSE-9912' },
        hash: '9a21b302c401e18a9947814a093b1238f874e0d9b418e20235d9b13938f90382',
        previousHash: '7d85311904a43a0db02e1dd31f9b33a8e94fae4860b0d91244e05ef0319ed02e',
      },
    ],
  },
  {
    id: 'plan_0076',
    ticketId: 'TCK-2026-0076',
    title: 'WRP Kernel Fast Delta Engine Bridge & API Sync',
    description: 'Implement continuous daemon kernel sync from vision.receipts to WRP Kernel API server on port 3103.',
    specId: 'SPEC-KERNEL-002',
    status: 'PENDING',
    currentRole: 'planner',
    modelChain: ['gemini-1.5-pro', 'claude-3-5-sonnet'],
    activeModel: 'gemini-1.5-pro',
    costUsd: 4.20,
    tokenCount: 185000,
    createdAt: '2026-07-23T15:00:00Z',
    updatedAt: '2026-07-24T09:00:00Z',
    retryAttempts: 0,
    receipts: [
      {
        id: 'RCP-0076-1',
        ticketId: 'TCK-2026-0076',
        receiptType: 'PROPOSED',
        issuedAt: '2026-07-23T15:10:00Z',
        payload: { proposedBy: 'KernelGuardAgent' },
        hash: '4101e4a7791a890479d59218d6e355b62b1b53f6511b0177721867c21f9f257a',
      },
      {
        id: 'RCP-0076-2',
        ticketId: 'TCK-2026-0076',
        receiptType: 'PLANNING',
        issuedAt: '2026-07-23T18:30:00Z',
        payload: { plannerModel: 'gemini-1.5-pro' },
        hash: 'b14067a3036e7885b9b7e9a2632b5f38a3d53784e037b51e44208e23f958a08a',
        previousHash: '4101e4a7791a890479d59218d6e355b62b1b53f6511b0177721867c21f9f257a',
      },
    ],
  },
  {
    id: 'plan_0074',
    ticketId: 'TCK-2026-0074',
    title: 'CCNF Conformance Bridge for Deterministic Work Requests',
    description: 'Ensure all DCOs emitted conform strictly to CCNF schema specifications for replay safety.',
    status: 'COMPLETED',
    currentRole: 'reviewer',
    modelChain: ['claude-3-5-sonnet'],
    activeModel: 'claude-3-5-sonnet',
    costUsd: 22.10,
    tokenCount: 680000,
    createdAt: '2026-07-18T10:00:00Z',
    updatedAt: '2026-07-21T16:00:00Z',
    retryAttempts: 0,
    receipts: [
      {
        id: 'RCP-0074-1',
        ticketId: 'TCK-2026-0074',
        receiptType: 'PROPOSED',
        issuedAt: '2026-07-18T10:05:00Z',
        payload: { proposedBy: 'CCNFBot' },
        hash: '6a0d0a77a560e7f7815668e16f30f5d720b001a1d950153f3e0d8b5c9314d101',
      },
      {
        id: 'RCP-0074-2',
        ticketId: 'TCK-2026-0074',
        receiptType: 'REVIEW_PASS',
        issuedAt: '2026-07-21T16:00:00Z',
        payload: { reviewedBy: 'ReviewerAuthority', result: 'APPROVED' },
        hash: 'f5869408422471900a3000b9533f01b17b6d1e4e4604b1f48612455856711d94',
        previousHash: '6a0d0a77a560e7f7815668e16f30f5d720b001a1d950153f3e0d8b5c9314d101',
      },
    ],
  },
  {
    id: 'plan_0073',
    ticketId: 'TCK-2026-0073',
    title: 'High-Volume Batch Token Cost Ceiling Guard',
    description: 'Automatic plan blocking when token costs exceed $500 threshold.',
    status: 'BLOCKED',
    currentRole: 'builder',
    modelChain: ['claude-3-5-sonnet'],
    activeModel: 'claude-3-5-sonnet',
    costUsd: 512.40,
    tokenCount: 15400000,
    createdAt: '2026-07-17T09:00:00Z',
    updatedAt: '2026-07-17T14:22:00Z',
    retryAttempts: 2,
    blockReason: 'Exit Code 4: Agent budget ceiling ($500.00) exceeded on tackle.agent_budget_usage',
    receipts: [
      {
        id: 'RCP-0073-1',
        ticketId: 'TCK-2026-0073',
        receiptType: 'BLOCK',
        issuedAt: '2026-07-17T14:22:00Z',
        payload: { exitCode: 4, reason: 'Budget Ceiling Exceeded', totalUsageUsd: 512.40 },
        hash: '228373b5a1b32d20d7e45667a421b8c19987b40d4218f0a0e9c80d55e81f1e9c',
      },
    ],
  },
];

export const INITIAL_WORK_REQUESTS: WorkRequestDCO[] = [
  {
    id: 'WR-2026-088',
    planId: 'plan_0075',
    role: 'builder',
    leaseId: 'LSE-9912',
    leaseOwner: 'executor-cloud-node-01',
    leaseExpiresAt: '2026-07-24T12:30:00Z',
    attemptId: 'ATT-2026-0441',
    attemptStatus: 'IN_PROGRESS',
    primaryModel: 'claude-3-5-sonnet',
    inputPayload: JSON.stringify(
      {
        dcoVersion: '1.2.0',
        action: 'BUILD_MODEL_CHAIN_DISPATCHER',
        targetFiles: ['main.py', 'db_adapter.py'],
        parameters: { maxRetries: 5, retryDelaySeconds: 300, enableFallback: true },
      },
      null,
      2
    ),
    costEstimateUsd: 3.40,
    createdAt: '2026-07-24T10:15:00Z',
  },
  {
    id: 'WR-2026-089',
    planId: 'plan_0075',
    role: 'planner',
    leaseId: 'LSE-9910',
    leaseOwner: 'cli-executor-local',
    leaseExpiresAt: '2026-07-24T11:00:00Z',
    attemptId: 'ATT-2026-0440',
    attemptStatus: 'SUCCEEDED',
    primaryModel: 'gemini-1.5-pro',
    inputPayload: JSON.stringify(
      {
        dcoVersion: '1.2.0',
        action: 'ELUCIDATE_PLAN_0075',
        outputArtifacts: ['IMPLEMENTATION_PLANS/0075_model_chain.md'],
      },
      null,
      2
    ),
    outputResult: JSON.stringify(
      {
        status: 'SUCCEEDED',
        exitCode: 0,
        generatedDcoCount: 2,
        tokensUsed: 124500,
        receiptHash: '7d85311904a43a0db02e1dd31f9b33a8e94fae4860b0d91244e05ef0319ed02e',
      },
      null,
      2
    ),
    executionReceiptHash: '7d85311904a43a0db02e1dd31f9b33a8e94fae4860b0d91244e05ef0319ed02e',
    costEstimateUsd: 1.85,
    createdAt: '2026-07-23T08:30:00Z',
    completedAt: '2026-07-23T08:34:12Z',
  },
  {
    id: 'WR-2026-087',
    planId: 'plan_0074',
    role: 'reviewer',
    leaseId: 'LSE-9880',
    leaseOwner: 'executor-cloud-node-02',
    leaseExpiresAt: '2026-07-21T16:30:00Z',
    attemptId: 'ATT-2026-0410',
    attemptStatus: 'SUCCEEDED',
    primaryModel: 'claude-3-5-sonnet',
    inputPayload: JSON.stringify({ action: 'VERIFY_CCNF_COMPLIANCE' }, null, 2),
    outputResult: JSON.stringify({ status: 'SUCCEEDED', ccnfScore: 100 }, null, 2),
    executionReceiptHash: 'f5869408422471900a3000b9533f01b17b6d1e4e4604b1f48612455856711d94',
    costEstimateUsd: 2.10,
    createdAt: '2026-07-21T15:00:00Z',
    completedAt: '2026-07-21T15:22:00Z',
  },
];

export const INITIAL_KERNEL_DELTAS: WRPKernelDelta[] = [
  {
    sequenceId: 1042,
    receiptId: 'RCP-0075-1',
    planId: 'plan_0075',
    action: 'PROPOSE_PLAN',
    deltaType: 'STATE_MUTATION',
    timestamp: '2026-07-22T17:05:00Z',
    engineSignature: 'WRP-ENGINE-v1.8.2',
    stateHash: '0x8f92a104b2c1',
  },
  {
    sequenceId: 1043,
    receiptId: 'RCP-0075-2',
    planId: 'plan_0075',
    action: 'PROMOTE_TO_PLANNING',
    deltaType: 'LINEAGE_LINK',
    timestamp: '2026-07-22T18:00:00Z',
    engineSignature: 'WRP-ENGINE-v1.8.2',
    stateHash: '0x991bc448a01f',
  },
  {
    sequenceId: 1044,
    receiptId: 'RCP-0075-3',
    planId: 'plan_0075',
    action: 'EMIT_WORK_REQUESTS',
    deltaType: 'STATE_MUTATION',
    timestamp: '2026-07-23T08:30:00Z',
    engineSignature: 'WRP-ENGINE-v1.8.2',
    stateHash: '0xa411d78e390c',
  },
  {
    sequenceId: 1045,
    receiptId: 'RCP-0075-4',
    planId: 'plan_0075',
    action: 'ACQUIRE_ADR006_LEASE',
    deltaType: 'SNAPSHOT_POINT',
    timestamp: '2026-07-24T10:15:00Z',
    engineSignature: 'WRP-ENGINE-v1.8.2',
    stateHash: '0xb233f89011de',
  },
];

export const INITIAL_SYSTEM_NODES: SystemNode[] = [
  {
    id: 'SYS-NEXUS-CORE',
    name: 'Nexus Organization Engine',
    type: 'system',
    description: 'Core organizational orchestrator and process control plane.',
    status: 'healthy',
    linkedSpecsCount: 4,
    linkedWorkRequestsCount: 12,
    children: [
      {
        id: 'SYS-CONDUIT',
        name: 'Conduit Orchestrator',
        type: 'subsystem',
        description: 'Cron-driven task dispatcher with PostgreSQL backend and Execution Authority.',
        status: 'healthy',
        linkedSpecsCount: 2,
        linkedWorkRequestsCount: 8,
        children: [
          {
            id: 'MOD-DISPATCHER',
            name: 'main.py & ModelChain',
            type: 'module',
            description: 'Model chain resolution, retry loops, and execution locks.',
            status: 'healthy',
            linkedSpecsCount: 1,
            linkedWorkRequestsCount: 4,
          },
          {
            id: 'MOD-DB-ADAPTER',
            name: 'db_adapter.py',
            type: 'module',
            description: 'PostgreSQL nexus interface for tickets, leases, attempts, and receipts.',
            status: 'healthy',
            linkedSpecsCount: 1,
            linkedWorkRequestsCount: 3,
          },
          {
            id: 'MOD-EXECUTOR-CLOUD',
            name: 'executor_cloud.py',
            type: 'module',
            description: 'Worker process parsing DCO, invoking opencode, writing results.',
            status: 'healthy',
            linkedSpecsCount: 1,
            linkedWorkRequestsCount: 1,
          },
        ],
      },
      {
        id: 'SYS-KERNEL',
        name: 'WRP Kernel Runtime',
        type: 'subsystem',
        description: 'Deterministic replay engine and state lineage validator.',
        status: 'healthy',
        linkedSpecsCount: 1,
        linkedWorkRequestsCount: 3,
        children: [
          {
            id: 'MOD-BRIDGE',
            name: 'bridge/ & conduit_bridge.py',
            type: 'module',
            description: 'Polls vision.receipts and generates KernelDeltas.',
            status: 'healthy',
            linkedSpecsCount: 1,
            linkedWorkRequestsCount: 2,
          },
          {
            id: 'MOD-API-SERVER',
            name: 'app/ (FastAPI port 3103)',
            type: 'module',
            description: 'Endpoints for /delta, /state, /replay, /metrics, /healthz.',
            status: 'healthy',
            linkedSpecsCount: 1,
            linkedWorkRequestsCount: 1,
          },
        ],
      },
    ],
  },
];

export const INITIAL_MODEL_CHAINS: ModelChainConfig[] = [
  {
    role: 'planner',
    primaryModel: 'gemini-1.5-pro',
    fallbackModels: ['claude-3-5-sonnet', 'gpt-4o-mini'],
    maxRetries: 5,
    retryDelaySeconds: 300,
    budgetCapUsd: 150.0,
    currentUsageUsd: 42.10,
    circuitBreakerTripped: false,
  },
  {
    role: 'builder',
    primaryModel: 'claude-3-5-sonnet',
    fallbackModels: ['gemini-1.5-pro', 'gpt-4o', 'PIPELINE_MODEL'],
    maxRetries: 5,
    retryDelaySeconds: 300,
    budgetCapUsd: 300.0,
    currentUsageUsd: 184.50,
    circuitBreakerTripped: false,
  },
  {
    role: 'reviewer',
    primaryModel: 'claude-3-5-sonnet',
    fallbackModels: ['gpt-4o', 'gemini-1.5-pro'],
    maxRetries: 3,
    retryDelaySeconds: 180,
    budgetCapUsd: 100.0,
    currentUsageUsd: 28.30,
    circuitBreakerTripped: false,
  },
  {
    role: 'kernel',
    primaryModel: 'wrp-kernel-in-process',
    fallbackModels: ['gemini-1.5-flash'],
    maxRetries: 2,
    retryDelaySeconds: 60,
    budgetCapUsd: 50.0,
    currentUsageUsd: 6.80,
    circuitBreakerTripped: false,
  },
  {
    role: 'executor',
    primaryModel: 'opencode-cli-local',
    fallbackModels: ['executor-cloud-pod'],
    maxRetries: 5,
    retryDelaySeconds: 300,
    budgetCapUsd: 250.0,
    currentUsageUsd: 91.20,
    circuitBreakerTripped: false,
  },
];
